server:
  port: 8085
  error:
    include-message: always
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productdb
      #uri: mongodb://localhost:27017/productdb
      
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9091/eureka/      
